{% set version = "2.5.2" %}

package:
  name: muscat-split
  version: {{ version }}


source:
  url: https://gitlab.com/drti/muscat/-/archive/{{ version }}/muscat-{{ version }}.tar.bz2
  sha256: cdedf793ed30dcaa3c87596aaad1ec8fe9f77711cc17716a67540a57aaa98c1a

build:
  number: 0


outputs:
  - name: muscat-core
    version: {{ version }}
    script: build_core.sh  # [linux]
    script: build_core_OsX.sh  # [osx]
    script: bld_core.bat  # [win]

    build:
      entry_points:
        - "MeshFileConvert = Muscat.IO.MeshFileConverter:Main"
      skip_compile_pyc: "MuscatParaViewPlugin.py"

    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        - ninja                                  # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
      host:
        - ninja
        - python
        # for the moment numpy 2 is activated only for python 3.13 (numpy 1 not available on py 3.13)
        - numpy >=2.*  # [py >= 313]
        - numpy =1.*  # [py < 313]
        - cython
        - sympy
        #first version of eigency compatible with numpy 2
        - eigency =3.4.0.4
        - mkl-devel
        - setuptools-scm
        - eigen
        - libboost-headers
        - llvm-openmp  # [osx]
        - libgomp      # [linux]
        - pip
        - setuptools
        - kokkos =4.7.01 h*  # [linux]
        - kokkos =4.4.01 h*  # [not linux]
        # mmg software api changes can break the bridge (for version)
        - mmgsuite =5.8
        - libscotch          # [not win]
        #so cmake can be tested before install
        - zlib
        - scipy >=1.12
        - dill
        - pywin32
        - networkx >=3.0
        # cvxpy not available in osx for numpy 2 (numpy 1 not available on python 3.13)
        - cvxpy  # [not osx or py!=313 ]
        - h5py
        - matplotlib-base
        - pycgns-core
        - mumps-seq   # [not osx]
        - mumps-include   # [linux]
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - scipy >=1.12
        - sympy
        - eigency =3.4.0.4
        - networkx >=3.0
        - dill
        - pywin32  # [win]
        - kokkos =4.7.01 h*  # [linux]
        - kokkos =4.4.01 h*  # [not linux]
        - mmgsuite =5.8
    test:
      requires:
        - scipy
        - cvxpy  # [not osx or py!=313 ]
        - h5py
        - matplotlib-base
        - pycgns-core
        - mumps-seq   # [not osx]
      imports:
        - Muscat
      commands:
        - python -u -m Muscat.Helpers.Check -k Which -k Mumps  # [osx]
        - python -u -m Muscat.Helpers.Check  # [linux]
        - python -u -m Muscat.Helpers.Check -k AnisotropicMetricComputation -k Mumps  # [win]

  - name: "muscat-extensions"
    version: {{ version }}
    requirements:
      host:
        - python
        - numpy >=2.*  # [py >= 313]
        - numpy =1.*  # [py < 313]
        - vtk <=9.4.2
        - psutil
        - h5py
        - meshio
        - pyvista
        - networkx >=3.0
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - vtk <=9.4.2
        - psutil
        - h5py
        - meshio
        - pyvista
        - networkx >=3.0
        - mmgsuite =5.8
        - cvxpy  # [not osx or py!=313 ]
        - pycgns-core
        - mumps-seq   # [not osx]
    test:
      imports:
        - psutil
        - h5py
        - meshio
        - networkx

  - name: "muscat"
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage('muscat-core', max_pin='x.x.x') }}
        - {{ pin_subpackage('muscat-extensions', max_pin='x.x.x') }}
    test:
      imports:
        - Muscat
      commands:
        - python -u -m Muscat.Helpers.Check -k Which -k Mumps  # [osx]
        - python -u -m Muscat.Helpers.Check  # [linux]
        - python -u -m Muscat.Helpers.Check -k AnisotropicMetricComputation   # [win]

  - name: "muscat-devenv"
    version: {{ version }}
    requirements:
      run:
        - {{ compiler('cxx') }}
        - python
        - numpy >=2.*  # [py >= 313]
        - numpy =1.*  # [py < 313]
        - sympy
        - cython
        - eigency =3.4.0.4
        - mkl-devel
        - setuptools-scm
        - eigen
        - scipy >=1.9
        - h5py
        - networkx >=3.0
        - libboost-headers
        - pytest
        - vtk <=9.4.2
        - matplotlib-base
        - coverage
        - pywin32  # [win]
        - dill
        - cmake
        - kokkos =4.7.01 h*  # [linux]
        - kokkos =4.4.01 h*  # [not linux]
        - mmgsuite =5.8
        - pycgns-core
        - cvxpy  # [not osx or py!=313 ]
    test:
      imports:
        - numpy

about:
  home: https://gitlab.com/drti/muscat
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Tools for finite element computations

extra:
  recipe-maintainers:
    - fbordeu
    - laureleen06
    - casenave
